### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException Unable to start activity ComponentInfo{com.netease.nis.quicklogin.ui.YDQuickLoginActivity}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by kaixinmaolv** [yidun/quickpass-android-demo#16]
Caused by java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner(ViewGroup.java:5325)
       at android.view.ViewGroup.addView(ViewGroup.java:5145)
       at android.view.ViewGroup.addView(ViewGroup.java:5085)
       at android.view.ViewGroup.addView(ViewGroup.java:5057)
       at com.netease.nis.quicklogin.ui.YDQuickLoginActivity.c(YDQuickLoginActivity.java:18)
       at com.netease.nis.quicklogin.ui.YDQuickLoginActivity.onCreate(YDQuickLoginActivity.java:3)
       at android.app.Activity.performCreate(Activity.java:8936)
       at android.app.Activity.performCreate(Activity.java:8900)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4277)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4449)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2846)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:328)
       at android.app.ActivityThread.main(ActivityThread.java:9210)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)

**Comment by kaixinmaolv** [comment]
请问这个问题怎么解决
